# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Block_DIagram/Block_DIagram.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_DIagram || ORIG_REF_NAME==Block_DIagram} -quiet] -quiet

# IP: bd/Block_DIagram/ip/Block_DIagram_processing_system7_0_0/Block_DIagram_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_DIagram_processing_system7_0_0 || ORIG_REF_NAME==Block_DIagram_processing_system7_0_0} -quiet] -quiet

# IP: bd/Block_DIagram/ip/Block_DIagram_SDC_Monitor_CAR_0_1/Block_DIagram_SDC_Monitor_CAR_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_DIagram_SDC_Monitor_CAR_0_1 || ORIG_REF_NAME==Block_DIagram_SDC_Monitor_CAR_0_1} -quiet] -quiet

# IP: bd/Block_DIagram/ip/Block_DIagram_axi_gpio_0_0/Block_DIagram_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_DIagram_axi_gpio_0_0 || ORIG_REF_NAME==Block_DIagram_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Block_DIagram/ip/Block_DIagram_ps7_0_axi_periph_0/Block_DIagram_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_DIagram_ps7_0_axi_periph_0 || ORIG_REF_NAME==Block_DIagram_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Block_DIagram/ip/Block_DIagram_rst_ps7_0_100M_0/Block_DIagram_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_DIagram_rst_ps7_0_100M_0 || ORIG_REF_NAME==Block_DIagram_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Block_DIagram/ip/Block_DIagram_auto_pc_0/Block_DIagram_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_DIagram_auto_pc_0 || ORIG_REF_NAME==Block_DIagram_auto_pc_0} -quiet] -quiet

# XDC: c:/B_Git/MCS/MC/MC_V1_Zybo/Vivado/project_1.gen/sources_1/bd/Block_DIagram/Block_DIagram_ooc.xdc
