
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include <ucos_bsp.h>
#include "ucos_axitimer.h"

/*
* The configuration table for devices
*/

UCOS_AXITIMER_Config UCOS_AXITIMER_ConfigTable[] =
{
	{
		XPAR_AXI_TIMER_0_DEVICE_ID,
		XPAR_AXI_TIMER_0_BASEADDR,
		XPAR_AXI_TIMER_0_CLOCK_FREQ_HZ,
		XPAR_AXI_TIMER_0_INT_SOURCE
	}
};


