# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Zybo_Constraints.xdc

# Block Designs: bd/Block_Diagram/Block_Diagram.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram || ORIG_REF_NAME==Block_Diagram} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_processing_system7_0_0/Block_Diagram_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_processing_system7_0_0 || ORIG_REF_NAME==Block_Diagram_processing_system7_0_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_SDC_Monitor_CAR_0_0/Block_Diagram_SDC_Monitor_CAR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_SDC_Monitor_CAR_0_0 || ORIG_REF_NAME==Block_Diagram_SDC_Monitor_CAR_0_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_axi_gpio_0_0/Block_Diagram_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_axi_gpio_0_0 || ORIG_REF_NAME==Block_Diagram_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_ps7_0_axi_periph_0/Block_Diagram_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_ps7_0_axi_periph_0 || ORIG_REF_NAME==Block_Diagram_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_rst_ps7_0_100M_0/Block_Diagram_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_rst_ps7_0_100M_0 || ORIG_REF_NAME==Block_Diagram_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_xlconstant_0_0/Block_Diagram_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_xlconstant_0_0 || ORIG_REF_NAME==Block_Diagram_xlconstant_0_0} -quiet] -quiet

# IP: bd/Block_Diagram/ip/Block_Diagram_auto_pc_0/Block_Diagram_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_Diagram_auto_pc_0 || ORIG_REF_NAME==Block_Diagram_auto_pc_0} -quiet] -quiet

# XDC: c:/B_Git/MCS/MC/MC_Zybo_V1/Vivado/Vivado.gen/sources_1/bd/Block_Diagram/Block_Diagram_ooc.xdc
