domain_path: C:\Git\GitHub\MCS\Drivers\INTR_WRPP\MIO_vs_EMIO_interrupt\Vitis\platform_SJJ_V2\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
