domain_path: C:\Git\GitHub\MCS\Drivers\Timer_INTR\Vitis\platform_V2\export\platform_V2\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
