# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Git/GitHub/MCS/MC/MC_state_machine/V1/Vivado/Vivado.srcs/sources_1/bd/MC/ip/MC_xadc_wiz_0_0/MC_xadc_wiz_0_0.xci
# IP: The module: 'MC_xadc_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Git/GitHub/MCS/MC/MC_state_machine/V1/Vivado/Vivado.gen/sources_1/bd/MC/ip/MC_xadc_wiz_0_0/MC_xadc_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MC_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Git/GitHub/MCS/MC/MC_state_machine/V1/Vivado/Vivado.gen/sources_1/bd/MC/ip/MC_xadc_wiz_0_0/MC_xadc_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MC_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Git/GitHub/MCS/MC/MC_state_machine/V1/Vivado/Vivado.srcs/sources_1/bd/MC/ip/MC_xadc_wiz_0_0/MC_xadc_wiz_0_0.xci
# IP: The module: 'MC_xadc_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Git/GitHub/MCS/MC/MC_state_machine/V1/Vivado/Vivado.gen/sources_1/bd/MC/ip/MC_xadc_wiz_0_0/MC_xadc_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MC_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Git/GitHub/MCS/MC/MC_state_machine/V1/Vivado/Vivado.gen/sources_1/bd/MC/ip/MC_xadc_wiz_0_0/MC_xadc_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'MC_xadc_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
