# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/myConstraints.xdc

# Block Designs: bd/BD/BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD || ORIG_REF_NAME==BD} -quiet] -quiet

# IP: bd/BD/ip/BD_processing_system7_0_0/BD_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==BD_processing_system7_0_0 || ORIG_REF_NAME==BD_processing_system7_0_0} -quiet] -quiet

# XDC: c:/B_Git/MCS/Drivers/CAN_Test/Vivado2/Vivado2.gen/sources_1/bd/BD/BD_ooc.xdc
