
TYPE
	constant_typ : 	STRUCT 
		MAX_NEG_TORQUE : REAL;
		MAX_BRAKE_PRESSURE : REAL;
		MIN_BRAKE_PRESSURE : REAL;
		REGEN_DERATING_SPEED : REAL;
		MIN_REGEN_SPEED : REAL;
		MIN_REGENERATION_VOLTAGE : REAL;
		PI : REAL;
		GEAR_RATIO : REAL;
		WHEEL_RADIUS : REAL;
		STEERING_ANGLE_MAX : REAL;
		MAX_TORQUE_VECTORING_DERATING : REAL;
		LAUNCH_PROFILE_MIN_TORQUE_PERC : REAL;
		LAUNCH_PROFILE_MIN_TORQUE : REAL;
		LAUNCH_PROFILE_MIN_SPEED : REAL;
		DERATING_AT_MAX : REAL;
		DERATING_AREA_WIDTH : REAL;
		REAR_DISTRIBUTION : REAL;
		FRONT_DISTRIBUTION : REAL;
		TORQUE_CONSTANT : REAL;
		MAX_TORQUE : REAL;
		NOMINAL_TORQUE : REAL;
	END_STRUCT;
	CONTROL_STATES : 
		(
		SIMPLE,
		NONE
		);
	control_typ : 	STRUCT 
		TV : torqueVectoring;
		TC : tractionControl;
		PL : powerLimiter;
		LP : launchProfile;
		TL : torqueLimiter;
		RB : regenerativeBraking;
	END_STRUCT;
END_TYPE
