# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/B_Git/MCS/MC/MC_Zybo_V1/Vivado/Vivado.srcs/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_0_0/Block_Diagram_axi_gpio_0_0.xci
# IP: The module: 'Block_Diagram_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/B_Git/MCS/MC/MC_Zybo_V1/Vivado/Vivado.gen/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_0_0/Block_Diagram_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/B_Git/MCS/MC/MC_Zybo_V1/Vivado/Vivado.gen/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_0_0/Block_Diagram_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/B_Git/MCS/MC/MC_Zybo_V1/Vivado/Vivado.gen/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_0_0/Block_Diagram_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/B_Git/MCS/MC/MC_Zybo_V1/Vivado/Vivado.srcs/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_0_0/Block_Diagram_axi_gpio_0_0.xci
# IP: The module: 'Block_Diagram_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/B_Git/MCS/MC/MC_Zybo_V1/Vivado/Vivado.gen/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_0_0/Block_Diagram_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/B_Git/MCS/MC/MC_Zybo_V1/Vivado/Vivado.gen/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_0_0/Block_Diagram_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/B_Git/MCS/MC/MC_Zybo_V1/Vivado/Vivado.gen/sources_1/bd/Block_Diagram/ip/Block_Diagram_axi_gpio_0_0/Block_Diagram_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_Diagram_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
