
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_PL_LEDS_DEVICE_ID,
		XPAR_PL_LEDS_BASEADDR,
		XPAR_PL_LEDS_INTERRUPT_PRESENT,
		XPAR_PL_LEDS_IS_DUAL
	},
	{
		XPAR_RELAY_DEVICE_ID,
		XPAR_RELAY_BASEADDR,
		XPAR_RELAY_INTERRUPT_PRESENT,
		XPAR_RELAY_IS_DUAL
	},
	{
		XPAR_SHUTDOWN_DEVICE_ID,
		XPAR_SHUTDOWN_BASEADDR,
		XPAR_SHUTDOWN_INTERRUPT_PRESENT,
		XPAR_SHUTDOWN_IS_DUAL
	}
};


