domain_path: C:\B_Git\MCS\MC\MC_Zybo_V1\Vitis\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Vitis\2024.1\data\embeddedsw\lib\sw_apps\peripheral_tests
template: peripheral_tests
