# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Constraints.xdc

# Block Designs: bd/MC/MC.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MC || ORIG_REF_NAME==MC} -quiet] -quiet

# IP: bd/MC/ip/MC_processing_system7_0_0/MC_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MC_processing_system7_0_0 || ORIG_REF_NAME==MC_processing_system7_0_0} -quiet] -quiet

# IP: bd/MC/ip/MC_xbar_0/MC_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MC_xbar_0 || ORIG_REF_NAME==MC_xbar_0} -quiet] -quiet

# IP: bd/MC/ip/MC_auto_pc_0/MC_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MC_auto_pc_0 || ORIG_REF_NAME==MC_auto_pc_0} -quiet] -quiet

# IP: bd/MC/ip/MC_ps7_0_axi_periph_0/MC_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MC_ps7_0_axi_periph_0 || ORIG_REF_NAME==MC_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/MC/ip/MC_rst_ps7_0_100M_0/MC_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MC_rst_ps7_0_100M_0 || ORIG_REF_NAME==MC_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/MC/ip/MC_xlconstant_0_0/MC_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MC_xlconstant_0_0 || ORIG_REF_NAME==MC_xlconstant_0_0} -quiet] -quiet

# IP: bd/MC/ip/MC_xlconstant_2_0/MC_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MC_xlconstant_2_0 || ORIG_REF_NAME==MC_xlconstant_2_0} -quiet] -quiet

# IP: bd/MC/ip/MC_xadc_wiz_0_0/MC_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MC_xadc_wiz_0_0 || ORIG_REF_NAME==MC_xadc_wiz_0_0} -quiet] -quiet

# XDC: c:/Git/GitHub/MCS/MC/MC_state_machine_xADC/V1/Vivado/Vivado.gen/sources_1/bd/MC/MC_ooc.xdc
