domain_path: C:\Git\GitHub\MCS_driver\MCS\Drivers\INTR_TIMER\Vitis\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
