domain_path: c:\Users\miwoj\Desktop\Zybo\GPIO_Interrupt\Vitis\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
