set_property SRC_FILE_INFO {cfile:C:/B_Git/MCS/MC/MC_V1/Vivado/Vivado.srcs/constrs_1/new/Constraints.xdc rfile:../../../Vivado.srcs/constrs_1/new/Constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T11 [get_ports UART0_CTSN]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T10 [get_ports UART0_RTSN]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T12 [get_ports UART0_RX]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U12 [get_ports UART0_TX]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V13 [get_ports CAN_0_rx]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U13 [get_ports CAN_0_tx]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T15 [get_ports CAN_1_rx]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T14 [get_ports CAN_1_tx]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6 [get_ports SPI0_MISO_I]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V6 [get_ports SPI0_MOSI_O]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y13 [get_ports SPI0_SCLK_O]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y12 [get_ports SPI0_SS_O]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G18 [get_ports SDC_SUPPLY_I]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G17 [get_ports COCKPIT_EMERGENCY_I]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports BOTS_I]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H17 [get_ports INERTIA_I]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports L_EMERGENCY_BUTTON_I]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports R_EMERGENCY_BUTTON_I]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports FR_WHEEL_I]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports FL_WHEEL_I]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports RR_WHEEL_I]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J16 [get_ports RL_WHEEL_I]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V11 [get_ports TSMS_I]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T5 [get_ports {PL_ALIVE_LED[0]}]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[3]}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[4]}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[9]}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[11]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[13]}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[14]}]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[0]}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[7]}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[1]}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[5]}]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[10]}]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[2]}]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[6]}]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[8]}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[12]}]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[15]}]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[16]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list MC_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 17 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[0]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[1]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[2]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[3]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[4]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[5]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[6]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[7]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[8]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[9]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[10]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[11]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[12]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[13]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[14]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[15]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[16]}]]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list MC_i/SDC_Monitor_CAR_0/U0/startup_delay_1sec]]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
