
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include <ucos_bsp.h>
#include "ucos_sdps.h"

/*
* The configuration table for devices
*/

UCOS_SDPS_Config UCOS_SDPS_ConfigTable[] =
{
	{
		XPAR_PS7_SD_0_DEVICE_ID,
		XPAR_PS7_SD_0_BASEADDR,
		XPAR_PS7_SD_0_SDIO_CLK_FREQ_HZ,
		XPAR_PS7_SD_0_INT_SOURCE
	}
};


