
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "ucos_ttcps.h"

/*
* The configuration table for devices
*/

UCOS_TTCPS_Config UCOS_TTCPS_ConfigTable[] =
{
	{
		XPAR_PS7_TTC_0_DEVICE_ID,
		XPAR_PS7_TTC_0_BASEADDR,
		XPAR_PS7_TTC_0_TTC_CLK_FREQ_HZ
	},
	{
		XPAR_PS7_TTC_1_DEVICE_ID,
		XPAR_PS7_TTC_1_BASEADDR,
		XPAR_PS7_TTC_1_TTC_CLK_FREQ_HZ
	},
	{
		XPAR_PS7_TTC_2_DEVICE_ID,
		XPAR_PS7_TTC_2_BASEADDR,
		XPAR_PS7_TTC_2_TTC_CLK_FREQ_HZ
	}
};


