domain_path: C:\Git\GitHub\MCS\MC\MC_state_machine_all_functions\V2\Vitis\platform\export\platform\sw\freertos_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\freertos_hello_world
template: freertos_hello_world
