domain_path: C:\Git\GitHub\MCS\Drivers\INTR_WRPP\Vitis\platform_intr_multiple_sources\export\platform_intr_multiple_sources\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
