domain_path: C:\Git\GitHub\MCS\Drivers\FreeRTOS\xADC\Vitis\platform_V1\export\platform_V1\sw\freertos_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\freertos_hello_world
template: freertos_hello_world
