# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Soeren-SDU/Downloads/Timer/Vivado/Vivado.srcs/sources_1/bd/MC/ip/MC_xbar_0/MC_xbar_0.xci
# IP: The module: 'MC_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Soeren-SDU/Downloads/Timer/Vivado/Vivado.gen/sources_1/bd/MC/ip/MC_xbar_0/MC_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MC_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Soeren-SDU/Downloads/Timer/Vivado/Vivado.srcs/sources_1/bd/MC/ip/MC_xbar_0/MC_xbar_0.xci
# IP: The module: 'MC_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Soeren-SDU/Downloads/Timer/Vivado/Vivado.gen/sources_1/bd/MC/ip/MC_xbar_0/MC_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MC_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
