# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/B_Git/MCS/MC/MC_V1_Zybo/Vivado/project_1.srcs/sources_1/bd/Block_DIagram/ip/Block_DIagram_processing_system7_0_0/Block_DIagram_processing_system7_0_0.xci
# IP: The module: 'Block_DIagram_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/B_Git/MCS/MC/MC_V1_Zybo/Vivado/project_1.gen/sources_1/bd/Block_DIagram/ip/Block_DIagram_processing_system7_0_0/Block_DIagram_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_DIagram_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/B_Git/MCS/MC/MC_V1_Zybo/Vivado/project_1.srcs/sources_1/bd/Block_DIagram/ip/Block_DIagram_processing_system7_0_0/Block_DIagram_processing_system7_0_0.xci
# IP: The module: 'Block_DIagram_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/B_Git/MCS/MC/MC_V1_Zybo/Vivado/project_1.gen/sources_1/bd/Block_DIagram/ip/Block_DIagram_processing_system7_0_0/Block_DIagram_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Block_DIagram_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
