domain_path: C:\Git\GitHub\MCS\MC\Hello_world\Vitis\Hello_world\export\Hello_world\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
