set_property SRC_FILE_INFO {cfile:c:/Git/GitHub/MCS/MC/MC_state_machine/V1/Vivado/Vivado.gen/sources_1/bd/MC/ip/MC_processing_system7_0_0/MC_processing_system7_0_0.xdc rfile:../Vivado.gen/sources_1/bd/MC/ip/MC_processing_system7_0_0/MC_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:MC_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Git/GitHub/MCS/MC/MC_state_machine/V1/Vivado/Vivado.gen/sources_1/bd/MC/ip/MC_rst_ps7_0_100M_0/MC_rst_ps7_0_100M_0.xdc rfile:../Vivado.gen/sources_1/bd/MC/ip/MC_rst_ps7_0_100M_0/MC_rst_ps7_0_100M_0.xdc id:2 order:EARLY scoped_inst:MC_i/rst_ps7_0_100M/U0} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Git/GitHub/MCS/MC/MC_state_machine/V1/Vivado/Vivado.srcs/constrs_1/new/Constraints.xdc rfile:../Vivado.srcs/constrs_1/new/Constraints.xdc id:3} [current_design]
current_instance MC_i/processing_system7_0/inst
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
current_instance
current_instance MC_i/rst_ps7_0_100M/U0
set_property src_info {type:SCOPED_XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "proc_sys_reset" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -quiet -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ */ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to}]]
current_instance
set_property src_info {type:XDC file:3 line:166 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:3 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:3 line:176 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list MC_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:3 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 17 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:179 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[0]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[1]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[2]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[3]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[4]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[5]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[6]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[7]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[8]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[9]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[10]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[11]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[12]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[13]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[14]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[15]} {MC_i/SDC_Monitor_CAR_0/U0/SDC_VECTOR_O[16]}]]
set_property src_info {type:XDC file:3 line:180 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:183 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list MC_i/SDC_Monitor_CAR_0/U0/startup_delay_1sec]]
set_property src_info {type:XDC file:3 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:187 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
